### ISSUE TITLE
bug：单页模式时若不配置template则打包时会报错，“You must supply options.input to rollup“

### ISSUE THREAD

**Issue by Xli33** [skymoonya/vite-plugin-htmlx#1]
文档说明在单页模式配置下，template有默认值为 index.html，不必要的话可以不用改，但实际不设具体值的话在打包时会报错“You must supply options.input to rollup”

可以看这个复现[demo](https://stackblitz.com/edit/vitejs-vite-hcvvxu?file=vite.config.js&terminal=dev)，只用了vite和插件

异常截图
![image](https://github.com/skymoonya/vite-plugin-htmlx/assets/28592778/f5d4f538-ea01-4551-a165-12b4fd913f6d)

建议直接改下文档好了，方便快捷o(*￣▽￣*)ブ

**Comment by skymoonya** [comment]
好的，晚点我修改一下

**Comment by skymoonya** [comment]
@Xli33 已经修复，还是保留了默认值~

**Comment by Xli33** [comment]
> @Xli33 已经修复，还是保留了默认值~

(๑‾ ꇴ ‾๑)好哒 ， 感谢大佬♪(･ω･)ﾉ
