### ISSUE TITLE
Windows上若设置了template，开发时找不到页面，而且停止开发后template文件会被删除

### ISSUE THREAD

**Issue by Xli33** [skymoonya/vite-plugin-htmlx#2]
可以在windows上用这个[demo](https://stackblitz.com/edit/vitejs-vite-lp4isk?file=vite.config.js,public%2Findex.html&terminal=dev)复现，有2个index.html主要是方便重现问题_(:з」∠)_

vite配置如下
```
import html from 'vite-plugin-htmlx';

export default {
  plugins: [
    html({
      // minify: true,
      page: {
        template: 'public/index.html',
      },
    }),
  ],
};
```
目前发现2个

- 一个是在开发时，启动正常，但实际找不到页面，而且每次停止开发模式后，index.html就会被删除
- 一个是打包后，dist/index.html 是未处理过的，而处理过的 index.html 还是在 dist/public/ 下面

而且跟使用的 html 位置无关，就算设置了 `index.html` 也还是有一样的问题o(╥﹏╥)o

**Comment by skymoonya** [comment]
好的，我晚点看一下，我是用mac开发的，忽略了在windows上的测试，抱歉

**Comment by Xli33** [comment]
> 好的，我晚点看一下，我是用mac开发的，忽略了在windows上的测试，抱歉

么事么事，大佬有空看下就好⁄(⁄ ⁄•⁄ω⁄•⁄ ⁄)⁄

**Comment by skymoonya** [comment]
@Xli33 已经修复 v1.0.3版本

**Comment by Xli33** [comment]
> @Xli33 已经修复 v1.0.3版本

@skymoonya 好哒，感谢大佬(･ω･)ﾉ
