### ISSUE TITLE
Getting "vite-plugin-htmlx' uses deprecated 'transform' option. Use 'handler' option instead." error message

### ISSUE THREAD

**Issue by bpetii** [skymoonya/vite-plugin-htmlx#4]
When I try to build my project, I get `plugin 'vite-plugin-htmlx' uses deprecated 'transform' option. Use 'handler' option instead` error message:

<img width="666" alt="Screenshot 2024-02-27 at 09 37 45" src="https://github.com/skymoonya/vite-plugin-htmlx/assets/36668443/94e7f85a-606f-4b82-bbd3-1317bd4af8c6">

<img width="871" alt="Screenshot 2024-02-27 at 09 38 13" src="https://github.com/skymoonya/vite-plugin-htmlx/assets/36668443/33967c9a-036f-4970-9756-9c6f61047da5">

**Comment by skymoonya** [comment]
@bpetii  I'm guessing your vite version is 5.x, in this version, `transformIndexHtml.transform` is deprecated and renamed to `handler`, I will update and release the new version as soon as possible
![image](https://github.com/skymoonya/vite-plugin-htmlx/assets/13905873/0b87c610-c1d7-4053-86a1-d023528ec94b)

**Comment by pahen** [comment]
> @bpetii I'm guessing your vite version is 5.x, in this version, `transformIndexHtml.transform` is deprecated and renamed to `handler`, I will update and release the new version as soon as possible

Any chance this is going to be fixed soon?

**Comment by skymoonya** [comment]
> > @bpetii I'm guessing your vite version is 5.x, in this version, `transformIndexHtml.transform` is deprecated and renamed to `handler`, I will update and release the new version as soon as possible
> 
> Any chance this is going to be fixed soon?

1.0.5 has been released

**Comment by pahen** [comment]
Thank you so much!  🙏
